name: Docker Build and Push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: ImageTag
        run: echo "tag=$(date '+%y%m%d%H%M')" >> $GITHUB_ENV
      
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: DockerHub Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: metiu19/sito-bootcamp:${{ env.tag }}
