name: Docker Build and Push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build Image
        run: |
          tag=$(date '+%y%m%d')
          docker build -t metiu19/sito-bootcamp:$tag .
      
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: DockerHub Push
        run: docker push metiu19/sito-bootcamp:$tag
